config/routes.rb
Graphcache::Application.routes.draw do
  resources :links

  get '/test' => 'nodes#test_twitter'

  resources :nodes do
    resources :links
  end

  root to: 'graphs#show'

  get '/graphs' => 'graphs#show'
  get '/graphs/d3data' => 'graphs#d3data'
  get '/followers' => 'graphs#followers'
  get '/friends' => 'graphs#friends'
  get '/id' => 'graphs#id'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/node.rb
class Node < ActiveRecord::Base
  attr_accessible :created_at, :description, :followers_count, :friends_count, :group_id, :id, :location, :name, :profile_image_url_https, :protected, :screen_name, :statuses_count

  validates :id, :presence => true
  validates :id, :uniqueness => true
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  include TwitterWrapper

  def test_twitter
    render :text => say_tweet
  end

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nodes }
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @node = Node.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/new
  # GET /nodes/new.json
  def new
    @node = Node.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    @node = Node.find(params[:id])
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(params[:node])

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render json: @node, status: :created, location: @node }
      else
        format.html { render action: "new" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nodes/1
  # PUT /nodes/1.json
  def update
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node = Node.find(params[:id])
    @node.destroy

    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :followers_count %><br />
    <%= f.number_field :followers_count %>
  </div>
  <div class="field">
    <%= f.label :friends_count %><br />
    <%= f.number_field :friends_count %>
  </div>
  <div class="field">
    <%= f.label :statuses_count %><br />
    <%= f.number_field :statuses_count %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.date_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :profile_image_url_https %><br />
    <%= f.text_area :profile_image_url_https %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :protected %><br />
    <%= f.check_box :protected %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.number_field :group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Followers count</th>
    <th>Friends count</th>
    <th>Statuses count</th>
    <th>Created at</th>
    <th>Profile image url https</th>
    <th>Description</th>
    <th>Location</th>
    <th>Name</th>
    <th>Protected</th>
    <th>Group</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nodes.each do |node| %>
  <tr>
    <td><%= node.id %></td>
    <td><%= node.followers_count %></td>
    <td><%= node.friends_count %></td>
    <td><%= node.statuses_count %></td>
    <td><%= node.created_at %></td>
    <td><%= node.profile_image_url_https %></td>
    <td><%= node.description %></td>
    <td><%= node.location %></td>
    <td><%= node.name %></td>
    <td><%= node.protected %></td>
    <td><%= node.group_id %></td>
    <td><%= link_to 'Show', node %></td>
    <td><%= link_to 'Edit', edit_node_path(node) %></td>
    <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @node.id %>
</p>

<p>
  <b>Followers count:</b>
  <%= @node.followers_count %>
</p>

<p>
  <b>Friends count:</b>
  <%= @node.friends_count %>
</p>

<p>
  <b>Statuses count:</b>
  <%= @node.statuses_count %>
</p>

<p>
  <b>Created at:</b>
  <%= @node.created_at %>
</p>

<p>
  <b>Profile image url https:</b>
  <%= @node.profile_image_url_https %>
</p>

<p>
  <b>Description:</b>
  <%= @node.description %>
</p>

<p>
  <b>Location:</b>
  <%= @node.location %>
</p>

<p>
  <b>Name:</b>
  <%= @node.name %>
</p>

<p>
  <b>Protected:</b>
  <%= @node.protected %>
</p>

<p>
  <b>Group:</b>
  <%= @node.group_id %>
</p>


<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>