config/routes.rb
Graphcache::Application.routes.draw do
  resources :links

  get '/test' => 'nodes#test_twitter'

  resources :nodes do
    resources :links
  end

  root to: 'graphs#show'

  get '/graphs' => 'graphs#show'
  get '/graphs/d3data' => 'graphs#d3data'
  get '/followers' => 'graphs#followers'
  get '/friends' => 'graphs#friends'
  get '/id' => 'graphs#id'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Graphcache" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">GraphCache</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <!-- <li><%= link_to "Nodes", nodes_path  %></li> -->
              <!-- <li><%= link_to "Links", links_path  %></li> -->
              <%= render :partial => 'graphs/form' %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9" id="main">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3" id="navbar">
            <% if current_user %>
              Signed in as <%= current_user.name %>!
              <%= link_to "Sign out", signout_path %>
            <% else %>
              <%= link_to "Sign in with Twitter", "/auth/twitter" %>
            <% end %>
          </div><!--/span-->
        </div><!--/row-->

      <footer>
   <!--     <p>&copy; Company 2013</p> -->
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="http://d3js.org/d3.v3.min.js"></script>
    <script type="text/javascript">
      if (typeof d3 == 'undefined') {
        document.write(unescape("%3Cscript src='/js/d3.v3.js' type='text/javascript'%3E%3C/script%3E"));
      }
    </script>
    <%= javascript_include_tag "application" %>

  </body>
</html>